import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../core/i18n.dart';
import '../../core/settings.dart';

typedef AiEntryStrings = ({
  String scanReceipt,
  String fromGallery,
  String enterManually,
  String addByVoice,
  String readingReceipt,
  String takesSeconds,
  String uploadFailed,
  String doubleCheck,
  String Function(String amount, String merchant) saved,
  String Function(String name) verified,
  String edit,
  String fallbackMerchant,
  String couldNotSave,
  String checkAndSave,
  String addTransaction,
  String expense,
  String income,
  String titlePlaceholder,
  String amountPlaceholder,
  String date,
  String save,
  String Function(int count) saveCount,
  String Function(int count) savedMany,
  String Function(int count) itemsSaved,
  String undo,
  String sayAgain,
  String saySpent,
  String understanding,
  String startRecording,
  String stopRecording,
  String close,
  String removeEntry,
  String micDenied,
  String micFailed,
  String noAudio,
  String processFailed,
  String fallbackVoiceTitle,
});

final Dict<AiEntryStrings> aiEntryStrings = (
  en: (
    scanReceipt: 'Scan receipt',
    fromGallery: 'Choose from gallery',
    enterManually: 'Enter manually',
    addByVoice: 'Add transaction by voice',
    readingReceipt: 'Reading receipt…',
    takesSeconds: 'This takes a few seconds',
    uploadFailed: 'Receipt upload failed',
    doubleCheck: 'Double-check the amount — the receipt was hard to read',
    saved: (amount, merchant) => 'Saved $amount₮ · $merchant',
    verified: (name) => 'Verified · $name',
    edit: 'Edit',
    fallbackMerchant: 'Receipt',
    couldNotSave: 'Could not save',
    checkAndSave: 'Check and save',
    addTransaction: 'Add transaction',
    expense: 'Expense',
    income: 'Income',
    titlePlaceholder: 'What was it?',
    amountPlaceholder: 'Amount',
    date: 'Date',
    save: 'Save',
    saveCount: (count) => 'Save $count',
    savedMany: (count) => 'Saved $count transactions',
    itemsSaved: (count) => '$count items · tap the transaction to see them',
    undo: 'Undo',
    sayAgain: 'Say again',
    saySpent: 'Say what you spent',
    understanding: 'Understanding…',
    startRecording: 'Start recording',
    stopRecording: 'Stop recording',
    close: 'Close',
    removeEntry: 'Remove this transaction',
    micDenied: 'Microphone access was denied',
    micFailed: 'Could not start the microphone',
    noAudio: 'No audio was recorded',
    processFailed: 'Could not process the recording',
    fallbackVoiceTitle: 'Voice entry',
  ),
  mn: (
    scanReceipt: 'Баримт уншуулах',
    fromGallery: 'Зургаас сонгох',
    enterManually: 'Гараар оруулах',
    addByVoice: 'Дуугаар гүйлгээ нэмэх',
    readingReceipt: 'Баримт уншиж байна…',
    takesSeconds: 'Хэдэн секунд болно',
    uploadFailed: 'Баримт илгээж чадсангүй',
    doubleCheck: 'Баримт тод уншигдсангүй — дүнгээ шалгана уу',
    saved: (amount, merchant) => '$amount₮ хадгаллаа · $merchant',
    verified: (name) => 'Баталгаажсан · $name',
    edit: 'Засах',
    fallbackMerchant: 'Баримт',
    couldNotSave: 'Хадгалж чадсангүй',
    checkAndSave: 'Шалгаад хадгална уу',
    addTransaction: 'Гүйлгээ нэмэх',
    expense: 'Зарлага',
    income: 'Орлого',
    titlePlaceholder: 'Юу вэ?',
    amountPlaceholder: 'Дүн',
    date: 'Огноо',
    save: 'Хадгалах',
    saveCount: (count) => '$count гүйлгээ хадгалах',
    savedMany: (count) => '$count гүйлгээ хадгаллаа',
    itemsSaved: (count) => '$count бараа · гүйлгээн дээр дарж харна уу',
    undo: 'Буцаах',
    sayAgain: 'Дахин хэлэх',
    saySpent: 'Юунд зарцуулснаа хэлээрэй',
    understanding: 'Ойлгож байна…',
    startRecording: 'Бичлэг эхлүүлэх',
    stopRecording: 'Бичлэг зогсоох',
    close: 'Хаах',
    removeEntry: 'Энэ гүйлгээг хасах',
    micDenied: 'Микрофон ашиглах зөвшөөрөл олгогдсонгүй',
    micFailed: 'Микрофоныг асааж чадсангүй',
    noAudio: 'Дуу бичигдсэнгүй',
    processFailed: 'Бичлэгийг боловсруулж чадсангүй',
    fallbackVoiceTitle: 'Дуут гүйлгээ',
  ),
);

/// Reads without subscribing, for use outside build methods.
AiEntryStrings readAiEntryStrings(WidgetRef ref) =>
    ref.read(localeProvider) == AppLocale.mn ? aiEntryStrings.mn : aiEntryStrings.en;
