import '../../core/i18n.dart';

typedef AuthStrings = ({
  String signInFailed,
  String signIn,
  String signUp,
  String welcome,
  String enterCredentials,
  String chooseMethod,
  String createToStart,
  String continueWithEmail,
  String continueWithGoogle,
  String redirecting,
  String noAccount,
  String haveAccount,
  String emailRequired,
  String emailInvalid,
  String passwordRequired,
  String passwordTooShort,
  String emailPlaceholder,
  String passwordPlaceholder,
  String newPasswordPlaceholder,
  String showPassword,
  String hidePassword,
  String signingIn,
  String continueLabel,
  String creatingAccount,
  String createAccount,
  String checkEmail,
});

const Dict<AuthStrings> authStrings = (
  en: (
    signInFailed: 'Sign-in failed. Please try again.',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    welcome: 'Welcome',
    enterCredentials: 'Enter your credentials to continue',
    chooseMethod: 'Choose your preferred sign-in method',
    createToStart: 'Create an account to get started',
    continueWithEmail: 'Continue with Email',
    continueWithGoogle: 'Continue with Google',
    redirecting: 'Redirecting…',
    noAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
    emailRequired: 'Email is required',
    emailInvalid: 'Please enter a valid email',
    passwordRequired: 'Password is required',
    passwordTooShort: 'Password must be at least 6 characters',
    emailPlaceholder: 'Enter your email',
    passwordPlaceholder: 'Enter your password',
    newPasswordPlaceholder: 'Create a password (6+ chars)',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    signingIn: 'Signing in…',
    continueLabel: 'Continue',
    creatingAccount: 'Creating account…',
    createAccount: 'Create Account',
    checkEmail: 'Check your email to confirm your account, then sign in.',
  ),
  mn: (
    signInFailed: 'Нэвтэрч чадсангүй. Дахин оролдоно уу.',
    signIn: 'Нэвтрэх',
    signUp: 'Бүртгүүлэх',
    welcome: 'Тавтай морил',
    enterCredentials: 'Үргэлжлүүлэхийн тулд мэдээллээ оруулна уу',
    chooseMethod: 'Нэвтрэх аргаа сонгоно уу',
    createToStart: 'Эхлэхийн тулд бүртгэл үүсгэнэ үү',
    continueWithEmail: 'Имэйлээр үргэлжлүүлэх',
    continueWithGoogle: 'Google-ээр үргэлжлүүлэх',
    redirecting: 'Шилжүүлж байна…',
    noAccount: 'Бүртгэлгүй юу?',
    haveAccount: 'Бүртгэлтэй юу?',
    emailRequired: 'Имэйл оруулна уу',
    emailInvalid: 'Зөв имэйл оруулна уу',
    passwordRequired: 'Нууц үг оруулна уу',
    passwordTooShort: 'Нууц үг дор хаяж 6 тэмдэгт байх ёстой',
    emailPlaceholder: 'Имэйлээ оруулна уу',
    passwordPlaceholder: 'Нууц үгээ оруулна уу',
    newPasswordPlaceholder: 'Нууц үг үүсгэх (6+ тэмдэгт)',
    showPassword: 'Нууц үг харуулах',
    hidePassword: 'Нууц үг нуух',
    signingIn: 'Нэвтэрч байна…',
    continueLabel: 'Үргэлжлүүлэх',
    creatingAccount: 'Бүртгэл үүсгэж байна…',
    createAccount: 'Бүртгэл үүсгэх',
    checkEmail: 'Бүртгэлээ баталгаажуулахын тулд имэйлээ шалгаад нэвтэрнэ үү.',
  ),
);
