import '../../core/i18n.dart';

typedef GoalErrorStrings = ({
  String titleRequired,
  String targetPositive,
  String invalidKind,
  String invalidImage,
  String invalidCategory,
  String invalidTargetDate,
  String contributionPositive,
  String pickPeriod,
  String pickStartDate,
  String signedOut,
  String tableMissing,
  String createFailed,
  String startingAmount,
  String amountPositive,
  String invalidDirection,
  String notFound,
  String overWithdraw,
});

typedef GoalsStrings = ({
  String newGoal,
  String addNewGoal,
  String back,
  String savings,
  String savingsHint,
  String plan,
  String planHint,
  String coverImage,
  String removeImage,
  String addPhoto,
  String imageTooLarge,
  String title,
  String savingsTitlePlaceholder,
  String planTitlePlaceholder,
  String targetAmount,
  String alreadySaved,
  String targetDate,
  String category,
  Map<String, String> categories,
  String contribute,
  String every,
  Map<String, String> periodOptions,
  Map<String, String> periodUnit,
  String startDate,
  String reminders,
  String remindDue,
  String remindMilestone,
  String autoContribute,
  String autoContributeHint,
  String createGoal,
  String goalCreated,
  String createFailed,
  String completed,
  String done,
  String saved,
  String Function(String) target,
  String Function(String) toGo,
  String addMoney,
  String withdraw,
  String started,
  String history,
  String noContributions,
  String deposit,
  String withdrawal,
  String addedToGoal,
  String withdrawnFromGoal,
  String deleteGoal,
  String Function(String) deleteConfirmTitle,
  String deleteConfirmBody,
  String cancel,
  String delete,
  String goalDeleted,
  String withdrawTitle,
  String depositTitle,
  String amount,
  String noteOptional,
  String notePlaceholder,
  String add,
  String loadFailed,
  GoalErrorStrings errors,
});

final Dict<GoalsStrings> goalsStrings = (
  en: (
    newGoal: 'New goal',
    addNewGoal: 'Add new goal',
    back: 'Back',
    savings: 'Savings',
    savingsHint: 'Save up to a target',
    plan: 'Plan',
    planHint: 'Fixed per period',
    coverImage: 'Cover image',
    removeImage: 'Remove image',
    addPhoto: 'Add a photo of your goal',
    imageTooLarge: 'Image must be 5 MB or smaller',
    title: 'Title',
    savingsTitlePlaceholder: 'New bicycle',
    planTitlePlaceholder: 'Emergency fund',
    targetAmount: 'Target amount',
    alreadySaved: 'Already saved',
    targetDate: 'Target date',
    category: 'Category',
    categories: const {
      'general': 'General',
      'travel': 'Travel',
      'gadget': 'Gadget',
      'home': 'Home',
      'emergency': 'Emergency fund',
    },
    contribute: 'Contribute',
    every: 'Every',
    periodOptions: const {'weekly': 'Week', 'monthly': 'Month', 'yearly': 'Year'},
    periodUnit: const {'weekly': 'week', 'monthly': 'month', 'yearly': 'year'},
    startDate: 'Start date',
    reminders: 'Reminders',
    remindDue: 'When a contribution is due',
    remindMilestone: 'At every 25% milestone',
    autoContribute: 'Auto-contribute',
    autoContributeHint: 'Log the contribution each period',
    createGoal: 'Create goal',
    goalCreated: 'Goal created',
    createFailed: 'Could not create goal',
    completed: 'Completed',
    done: 'Done',
    saved: 'Saved',
    target: (amount) => 'Target $amount',
    toGo: (amount) => '$amount to go',
    addMoney: 'Add money',
    withdraw: 'Withdraw',
    started: 'Started',
    history: 'History',
    noContributions: 'No contributions yet.',
    deposit: 'Deposit',
    withdrawal: 'Withdrawal',
    addedToGoal: 'Added to goal',
    withdrawnFromGoal: 'Withdrawn from goal',
    deleteGoal: 'Delete goal',
    deleteConfirmTitle: (title) => 'Delete “$title”?',
    deleteConfirmBody: 'The goal and its contribution history will be removed. This cannot be undone.',
    cancel: 'Cancel',
    delete: 'Delete',
    goalDeleted: 'Goal deleted',
    withdrawTitle: 'Withdraw from goal',
    depositTitle: 'Add money to goal',
    amount: 'Amount',
    noteOptional: 'Note (optional)',
    notePlaceholder: 'Salary bonus',
    add: 'Add',
    loadFailed: 'Could not load goal',
    errors: (
      titleRequired: 'Title is required',
      targetPositive: 'Enter a target greater than 0',
      invalidKind: 'Invalid goal type',
      invalidImage: 'Invalid image URL',
      invalidCategory: 'Invalid category',
      invalidTargetDate: 'Invalid target date',
      contributionPositive: 'Enter a contribution greater than 0',
      pickPeriod: 'Pick how often you contribute',
      pickStartDate: 'Pick a start date',
      signedOut: 'You must be signed in',
      tableMissing: 'Run supabase-goals.sql in Supabase to enable goals.',
      createFailed: 'Could not create goal',
      startingAmount: 'Starting amount',
      amountPositive: 'Enter an amount greater than 0',
      invalidDirection: 'Invalid direction',
      notFound: 'Goal not found',
      overWithdraw: "You can't withdraw more than you've saved",
    ),
  ),
  mn: (
    newGoal: 'Шинэ зорилго',
    addNewGoal: 'Зорилго нэмэх',
    back: 'Буцах',
    savings: 'Хуримтлал',
    savingsHint: 'Зорилтот дүн хүртэл хуримтлуулах',
    plan: 'Төлөвлөгөө',
    planHint: 'Үе бүр тогтмол дүн',
    coverImage: 'Нүүр зураг',
    removeImage: 'Зураг устгах',
    addPhoto: 'Зорилгынхоо зургийг нэмэх',
    imageTooLarge: 'Зураг 5 MB-аас ихгүй байх ёстой',
    title: 'Нэр',
    savingsTitlePlaceholder: 'Шинэ дугуй',
    planTitlePlaceholder: 'Яаралтай сан',
    targetAmount: 'Зорилтот дүн',
    alreadySaved: 'Хуримтлуулсан',
    targetDate: 'Зорилтот огноо',
    category: 'Ангилал',
    categories: const {
      'general': 'Ерөнхий',
      'travel': 'Аялал',
      'gadget': 'Төхөөрөмж',
      'home': 'Гэр',
      'emergency': 'Яаралтай сан',
    },
    contribute: 'Хуримтлуулах дүн',
    every: 'Давтамж',
    periodOptions: const {'weekly': '7 хоног', 'monthly': 'Сар', 'yearly': 'Жил'},
    periodUnit: const {'weekly': '7 хоног', 'monthly': 'сар', 'yearly': 'жил'},
    startDate: 'Эхлэх огноо',
    reminders: 'Сануулга',
    remindDue: 'Хуримтлуулах хугацаа болоход',
    remindMilestone: '25% хүрэх бүрт',
    autoContribute: 'Автомат хуримтлал',
    autoContributeHint: 'Үе бүр хуримтлалыг автоматаар бүртгэнэ',
    createGoal: 'Зорилго үүсгэх',
    goalCreated: 'Зорилго үүслээ',
    createFailed: 'Зорилго үүсгэж чадсангүй',
    completed: 'Биелсэн',
    done: 'Биелсэн',
    saved: 'Хуримтлуулсан',
    target: (amount) => 'Зорилт $amount',
    toGo: (amount) => '$amount дутуу',
    addMoney: 'Мөнгө нэмэх',
    withdraw: 'Авах',
    started: 'Эхэлсэн',
    history: 'Түүх',
    noContributions: 'Одоогоор гүйлгээ алга.',
    deposit: 'Нэмсэн',
    withdrawal: 'Авсан',
    addedToGoal: 'Зорилгод мөнгө нэмлээ',
    withdrawnFromGoal: 'Зорилгоос мөнгө авлаа',
    deleteGoal: 'Зорилго устгах',
    deleteConfirmTitle: (title) => '“$title”-г устгах уу?',
    deleteConfirmBody: 'Зорилго болон түүний гүйлгээний түүх устна. Буцаах боломжгүй.',
    cancel: 'Болих',
    delete: 'Устгах',
    goalDeleted: 'Зорилго устлаа',
    withdrawTitle: 'Зорилгоос мөнгө авах',
    depositTitle: 'Зорилгод мөнгө нэмэх',
    amount: 'Дүн',
    noteOptional: 'Тэмдэглэл (заавал биш)',
    notePlaceholder: 'Цалингийн урамшуулал',
    add: 'Нэмэх',
    loadFailed: 'Зорилго ачаалж чадсангүй',
    errors: (
      titleRequired: 'Нэр оруулна уу',
      targetPositive: '0-ээс их зорилтот дүн оруулна уу',
      invalidKind: 'Зорилгын төрөл буруу байна',
      invalidImage: 'Зургийн холбоос буруу байна',
      invalidCategory: 'Ангилал буруу байна',
      invalidTargetDate: 'Зорилтот огноо буруу байна',
      contributionPositive: '0-ээс их хуримтлуулах дүн оруулна уу',
      pickPeriod: 'Хуримтлуулах давтамжаа сонгоно уу',
      pickStartDate: 'Эхлэх огноо сонгоно уу',
      signedOut: 'Нэвтэрсэн байх шаардлагатай',
      tableMissing: 'Зорилго идэвхжүүлэхийн тулд Supabase-д supabase-goals.sql-г ажиллуулна уу.',
      createFailed: 'Зорилго үүсгэж чадсангүй',
      startingAmount: 'Эхний дүн',
      amountPositive: '0-ээс их дүн оруулна уу',
      invalidDirection: 'Гүйлгээний чиглэл буруу байна',
      notFound: 'Зорилго олдсонгүй',
      overWithdraw: 'Хуримтлуулснаасаа их мөнгө авах боломжгүй',
    ),
  ),
);
