import '../../core/i18n.dart';

typedef HomeStrings = ({
  String morning,
  String afternoon,
  String evening,
  String night,
  String totalBalance,
  String Function(int) percentOfIncome,
  String income,
  String expense,
  String transactions,
  String seeAll,
  String emptyTitle,
  String emptyHint,
  String today,
  String yesterday,
});

final Dict<HomeStrings> homeStrings = (
  en: (
    morning: 'Good Morning',
    afternoon: 'Good Afternoon',
    evening: 'Good Evening',
    night: 'Good Night',
    totalBalance: 'Total balance',
    percentOfIncome: (n) => '$n% of income',
    income: 'Income',
    expense: 'Expense',
    transactions: 'Transactions',
    seeAll: 'See all',
    emptyTitle: 'No transactions yet',
    emptyHint: 'Scan a receipt or add one manually to get started.',
    today: 'Today',
    yesterday: 'Yesterday',
  ),
  mn: (
    morning: 'Өглөөний мэнд',
    afternoon: 'Өдрийн мэнд',
    evening: 'Оройн мэнд',
    night: 'Шөнийн мэнд',
    totalBalance: 'Нийт үлдэгдэл',
    percentOfIncome: (n) => 'орлогын $n%',
    income: 'Орлого',
    expense: 'Зарлага',
    transactions: 'Гүйлгээ',
    seeAll: 'Бүгдийг харах',
    emptyTitle: 'Гүйлгээ алга байна',
    emptyHint: 'Баримт уншуулах эсвэл гараар нэмж эхлээрэй.',
    today: 'Өнөөдөр',
    yesterday: 'Өчигдөр',
  ),
);

typedef TxStrings = ({
  String allTransactions,
  String emptyTitle,
  String emptyHint,
  String details,
  String back,
  String editTransaction,
  String expense,
  String income,
  String title,
  String amount,
  String date,
  String category,
  String type,
  String added,
  String cancel,
  String delete,
  String receipt,
  String updated,
  String deleted,
  String Function(String) confirmDelete,
  String deleteTransaction,
  String notFound,
  String loadFailed,
  String Function(int) items,
  String itemsTotal,
  String Function(String, String) itemsMismatch,
});

final Dict<TxStrings> txStrings = (
  en: (
    allTransactions: 'All Transactions',
    emptyTitle: 'Nothing here yet',
    emptyHint: 'Transactions you add will show up here.',
    details: 'Details',
    back: 'Back',
    editTransaction: 'Edit transaction',
    expense: 'Expense',
    income: 'Income',
    title: 'Title',
    amount: 'Amount',
    date: 'Date',
    category: 'Category',
    type: 'Type',
    added: 'Added',
    cancel: 'Cancel',
    delete: 'Delete',
    receipt: 'Receipt',
    updated: 'Transaction updated',
    deleted: 'Transaction deleted',
    confirmDelete: (title) => 'Delete "$title"?',
    deleteTransaction: 'Delete transaction',
    notFound: 'Transaction not found',
    loadFailed: 'Could not load',
    items: (count) => 'Items · $count',
    itemsTotal: 'Items total',
    itemsMismatch: (sum, total) => 'Items add up to $sum, but the receipt total is $total.',
  ),
  mn: (
    allTransactions: 'Бүх гүйлгээ',
    emptyTitle: 'Одоогоор хоосон байна',
    emptyHint: 'Нэмсэн гүйлгээ тань энд харагдана.',
    details: 'Дэлгэрэнгүй',
    back: 'Буцах',
    editTransaction: 'Гүйлгээ засах',
    expense: 'Зарлага',
    income: 'Орлого',
    title: 'Нэр',
    amount: 'Дүн',
    date: 'Огноо',
    category: 'Ангилал',
    type: 'Төрөл',
    added: 'Нэмсэн',
    cancel: 'Цуцлах',
    delete: 'Устгах',
    receipt: 'Баримт',
    updated: 'Гүйлгээ шинэчлэгдлээ',
    deleted: 'Гүйлгээ устгагдлаа',
    confirmDelete: (title) => '"$title"-г устгах уу?',
    deleteTransaction: 'Гүйлгээ устгах',
    notFound: 'Гүйлгээ олдсонгүй',
    loadFailed: 'Ачаалж чадсангүй',
    items: (count) => 'Бараа · $count',
    itemsTotal: 'Барааны нийт дүн',
    itemsMismatch: (sum, total) => 'Барааны нийлбэр $sum боловч баримтын нийт дүн $total байна.',
  ),
);

typedef FormStrings = ({
  String addTransaction,
  String editTransaction,
  String expense,
  String income,
  String title,
  String amount,
  String date,
  String category,
  String expensePlaceholder,
  String incomePlaceholder,
  String titleRequired,
  String amountRequired,
  String amountPositive,
  String expenseSaved,
  String incomeSaved,
  String updated,
  String couldNotSave,
  String saving,
  String saveExpense,
  String saveIncome,
  String save,
});

const Dict<FormStrings> formStrings = (
  en: (
    addTransaction: 'Add transaction',
    editTransaction: 'Edit transaction',
    expense: 'Expense',
    income: 'Income',
    title: 'Title',
    amount: 'Amount',
    date: 'Date',
    category: 'Category',
    expensePlaceholder: 'Grocery shopping',
    incomePlaceholder: 'Salary',
    titleRequired: 'Title is required',
    amountRequired: 'Amount is required',
    amountPositive: 'Enter an amount greater than 0',
    expenseSaved: 'Expense saved',
    incomeSaved: 'Income saved',
    updated: 'Transaction updated',
    couldNotSave: 'Could not save',
    saving: 'Saving…',
    saveExpense: 'Save expense',
    saveIncome: 'Save income',
    save: 'Save',
  ),
  mn: (
    addTransaction: 'Гүйлгээ нэмэх',
    editTransaction: 'Гүйлгээ засах',
    expense: 'Зарлага',
    income: 'Орлого',
    title: 'Нэр',
    amount: 'Дүн',
    date: 'Огноо',
    category: 'Ангилал',
    expensePlaceholder: 'Хүнсний дэлгүүр',
    incomePlaceholder: 'Цалин',
    titleRequired: 'Нэр оруулна уу',
    amountRequired: 'Дүн оруулна уу',
    amountPositive: '0-ээс их дүн оруулна уу',
    expenseSaved: 'Зарлага хадгаллаа',
    incomeSaved: 'Орлого хадгаллаа',
    updated: 'Гүйлгээ шинэчлэгдлээ',
    couldNotSave: 'Хадгалж чадсангүй',
    saving: 'Хадгалж байна…',
    saveExpense: 'Зарлага хадгалах',
    saveIncome: 'Орлого хадгалах',
    save: 'Хадгалах',
  ),
);
